### ISSUE TITLE
Special characters in file names

### ISSUE THREAD

**Issue by alexaguado** [nokia/vscode-intent-manager#4]
Fix issue with filename using special characters that cause conflicts in vsCode: e.g. "/".

**Comment by wisotzky** [comment]
This issue only exists for auto-generated filenames for intents (intent-type instances). Especially in cases where port-id (CLI centric like 1/1/1) or XPATH expressions are used, the "/" character would typically appear.

The challenge is, that the virtual filesystem uses "/" in the URI as separator. The issue can be fixed, by using URI encoded filenames for intents. It might not look that pretty, but would do the job! Please confirm, and will update the code accordingly!

For intent-type folders the issue should not exit, because intent-type names must consist of small cap letters, numbers and dash-sign only. We are not expecting any special characters here.

**Comment by wisotzky** [comment]
Fixed in https://github.com/nokia/vscode-intent-manager/releases/tag/2.1.0
Filenames for intents are now URI encoded.
